services:
  database:
    container_name: mongodb
    image: mongo
  server:
    container_name: ilike
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3001:3001"
    restart: always